version: "3.8"

services:
  user_postgres:
    container_name: user_postgres
    image: "postgres:latest"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

volumes:
  user_postgres_data:
        
