server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user_pagination
    username: spring
    password: paginationFilterSearch
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml